services:
  pb:
    build:
      context: ./pb
      dockerfile: Dockerfile
    volumes:
      - ./pb/pb_migrations:/pb/pb_migrations
      - ./pb/pb_hooks:/pb/pb_hooks
      - pb_data:/pb/pb_data
    ports:
      - "8080:8080"
    environment:
      - MEILI_URL=${PB_MEILI_URL}
      - ENV=${ENV}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    env_file:
      - .env

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6389:6379"
    volumes:
      - ./redis/data:/redis/data

  crawl4ai:
    image: unclecode/crawl4ai
    ports:
      - "11235:11235"

  meilisearch:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch/data:/meili_data
    env_file:
      - .env
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}

  searxng:
    image: searxng/searxng
    ports:
      - "8888:8888"
    env_file:
      - .env

volumes:
  pb_data:
    driver: local
