# nixpacks.toml

providers = ["node"]

[staticAssets]
# (no entries)

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]
cacheDirectories = ["node_modules/.cache"]

[start]
cmd = "pnpm run start"

# [nixpkgs]
# packages = [
#   "poppler",       # for pdftotext (PDF support)
#   "antiword",      # for .doc
#   "unrtf",         # for .rtf
#   "catdoc",        # for .xls
#   "libreoffice",   # fallback document converter (heavy but useful)
#   "tesseract",     # OCR fallback (optional)
#   "bash"           # some parsers need shell to be available
# ]