services:
  pb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pb_data:/pb/pb_data
    environment:
      - MEILI_URL=${MEILI_URL}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - ENV=${ENV}
